# Generated by Django 2.0.4 on 2018-04-27 01:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20180426_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
